# Build setup steps for r2x CI
# These steps are used as a reference for setting up the build environment.

- name: Setup uv & Python
  uses: ./.github/actions/setup-uv-python
  with:
    python-version: "3.12"
