- name: Setup uv & Python
  uses: ./.github/actions/setup-uv-python
  with:
    python-version: "3.12"


- name: Prepare Python shim
  shell: bash
  run: |
    PY_VERSION=3.12 ./scripts/prepare_python_shim.sh
