name: "Setup uv & Python"
description: "Installs uv, sets up Python via uv, and configures PYO3_PYTHON environment variable"
inputs:
  python-version:
    description: 'Python version to install (e.g., "3.12")'
    required: true
    default: "3.12"
runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    - name: Install Python via uv and set PYO3_PYTHON
      shell: bash
      run: |
        uv python install ${{ inputs.python-version }}
        UV_PYTHON_BIN=$(uv python find ${{ inputs.python-version }})
        echo "PYO3_PYTHON=$UV_PYTHON_BIN" >> $GITHUB_ENV
        echo "Setting PYO3_PYTHON => $UV_PYTHON_BIN"
    - name: Fix libpython install name for portable builds
      if: runner.os == 'macOS'
      shell: bash
      run: |
        UV_PYTHON_BIN=$(uv python find ${{ inputs.python-version }})
        PYTHON_PREFIX=$(dirname "$(dirname "$UV_PYTHON_BIN")")
        LIBPYTHON="$PYTHON_PREFIX/lib/libpython${{ inputs.python-version }}.dylib"
        if [ -f "$LIBPYTHON" ]; then
          echo "Fixing libpython install name for portable binary linking"
          echo "  Before: $(otool -D "$LIBPYTHON" | tail -1)"
          install_name_tool -id "@rpath/libpython${{ inputs.python-version }}.dylib" "$LIBPYTHON"
          echo "  After:  $(otool -D "$LIBPYTHON" | tail -1)"
        else
          echo "libpython not found at $LIBPYTHON (skipping install name fix)"
        fi
