name: "Setup uv & Python"
description: "Installs uv, sets up Python via uv, and configures PYO3_PYTHON environment variable"
inputs:
  python-version:
    description: 'Python version to install (e.g., "3.12")'
    required: true
    default: "3.12"
  python-platform:
    description: 'Optional platform specifier (e.g., "x86_64-apple-darwin", "aarch64-apple-darwin")'
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Install uv & Python
      uses: astral-sh/setup-uv@v3
      with:
        python-version: ${{ inputs.python-version }}
    - name: Set PYO3_PYTHON to uv python
      shell: bash
      run: |
        if [[ -n "${{ inputs.python-platform }}" ]]; then
          PYTHON_SPEC="${{ inputs.python-version }}-${{ inputs.python-platform }}"
          echo "Installing Python with platform specifier: $PYTHON_SPEC"
          uv python install "$PYTHON_SPEC"
          UV_PYTHON_BIN=$(uv python find "$PYTHON_SPEC")
        else
          uv python install ${{ inputs.python-version }}
          UV_PYTHON_BIN=$(uv python find ${{ inputs.python-version }})
        fi
        echo "PYO3_PYTHON=$UV_PYTHON_BIN" >> $GITHUB_ENV
        echo "Setting PYO3_PYTHON => $UV_PYTHON_BIN"
